if (length(commandArgs(trailingOnly = TRUE))) stop("This fixed historical comparison takes no arguments.")
script <- grep("^--file=", commandArgs(), value = TRUE)
project <- if (length(script)) dirname(normalizePath(sub("^--file=", "", script[1]), winslash = "/")) else getwd()
for (file in c("config.R", "store.R", "features.R", "workflow.R")) source(file.path(project, "cfb_v2", file))
for (file in c("controlled_ats.R", "audit_og_inputs.R", "og_reconstruction.R", "external_ratings.R", "external_backtest.R"))
  source(file.path(project, "cfb_v3/experiments", file))
result <- run_external_backtest(project)
print(result$metrics, row.names = FALSE)
cat("Historical benchmark report:", file.path(result$output, "report.md"), "\n")
