if (length(commandArgs(trailingOnly = TRUE))) stop("This fixed experiment takes no arguments.")
script <- grep("^--file=", commandArgs(), value = TRUE)
project <- if (length(script)) dirname(normalizePath(sub("^--file=", "", script[1]), winslash = "/")) else getwd()
for (file in c("config.R", "store.R", "features.R", "models.R", "workflow.R")) source(file.path(project, "cfb_v2", file))
for (file in c("controlled_ats.R", "external_ratings.R", "tracker_edge.R"))
  source(file.path(project, "cfb_v3/experiments", file))
result <- run_tracker_edge(project)
print(result$summary, row.names = FALSE)
cat("Edge investigation report:", file.path(result$output, "REPORT.md"), "\n")
